### ISSUE TITLE
DevFestNantes - Opening, break and lunch sessions should not specify a room 

### ISSUE THREAD

**Issue by RobinCaroff** [joreilly/Confetti#108]
Opening, break and lunch sessions currently specify the room Belem but they should not indicate any room.

**Comment by RobinCaroff** [comment]
cc @martinbonnin 🎁🙂

**Comment by joreilly** [comment]
Assume some updates in back end data needed for this initially.....but I can update UI then I guess in case we still try to show some text there for those slots.

**Comment by RobinCaroff** [comment]
Yes `Session` used to have only the `room` attribute which probably forced @martinbonnin to provide a default value. But `Session`'s `room` has since been deprecated and replaced by `rooms:[Room]` which is more flexible and can be empty.

**Comment by RobinCaroff** [comment]
Btw many thanks for sharing Confetti's backend ! We're very grateful to you guys for the help provided to the DevFest Nantes!

**Comment by martinbonnin** [comment]
So that's an interesting question... At the moment, I believe breaks indicate all the rooms they apply to:

```json
    {
          "id": "day-1-pause-1",
          "startInstant": "2022-10-20T07:40:00Z",
          "endInstant": "2022-10-20T08:00:00Z",
          "title": "Break",
          "language": "fr-FR",
          "tags": [],
          "rooms": [
            {
              "id": "Belem"
            },
            {
              "id": "Hangar"
            },
            {
              "id": "Jules Verne"
            },
            {
              "id": "L'Atelier"
            },
            {
              "id": "Les Machines"
            },
            {
              "id": "Titan"
            },
            {
              "id": "Tour de Bretagne"
            }
          ],
```

This is because not all sessions are the same duration and longer workshop do not have the same breaks as regular sessions. Having this information allows a 2D-matrix UI (like on web) to only display the breaks where they actually happen. Now I agree that when using a 1D-linear UI (like on mobile), it doesn't really make sense. So not sure what the best fix is. I would like going forward to support 2D UI moving forward. The more I'm thinking about this, the more I believe we either:
1. need different "views" fields for the same underlying data
2. or do this on the client (but that'd duplicate some logic)
3. not support 2D UI for the Devfest Nantes and remove all rooms

My preferred solution would be 1. but I'm not super keen on changing this 2weeks from the event (+ taking into consideration Google Play review times, etc...) so I'll remove the rooms from the backend for this specific event. For other events, I'll work on adding new "views" for more use cases 🚀 

PS: I'm always amazed how difficult the problem of displaying an agenda is 😅 . That could be a talk in itself lol.

**Comment by martinbonnin** [comment]
Rooms are removed

**Comment by RobinCaroff** [comment]
@martinbonnin thanks for the quick fix. This is actually a very interesting issue and I hadn't thought of all the subtleties 🤔. Let's keep that in mind for future events. Surely there is something smart to do.
