### ISSUE TITLE
Indicate lightning talks in the UI

### ISSUE THREAD

**Issue by joreilly** [joreilly/Confetti#533]
Can be inferred we believe from the talk duration....see following for example https://kotlinconf.com/schedule/april-13/

<img width="785" alt="Screenshot 2023-04-06 at 11 50 20" src="https://user-images.githubusercontent.com/6302/230355920-af50ed32-84e9-49bf-988f-bc9d82161816.png">

**Comment by yschimke** [comment]
Shouldn't we put this sort of logic behind the server? perhaps with a more generic concept?

**Comment by StylianosGakis** [comment]
Aha, some sort of extra tag, which would support arbitrary text in there I presume?
I see that in the website they also have another similar tag which says "AWS lab", with a different icon. So yeah that'd probably be a good idea.

A question for this one, how would we be sending the icon to the clients from the server? Does Confetti right now have a place where such icons are hosted so that we can send the URL from the backend to the apps?

**Comment by joreilly** [comment]
@martinbonnin what do you think about having this in the backend?  We can probably close this particular issue for now and create new one if we think that's something we'd do

**Comment by martinbonnin** [comment]
Agreed, it'd be interesting to investigate some kind of server-driven rendering for this. There is already "session.tags" but it's very loosely coupled. Let's close this issue and revisit for Devoxx "quickies" ;)
